language: python
python: "2.7"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - pytest --cov=src tests/
after_success:
  - codecov
  - pytest --cov-report xml --cov=src tests/
  - python-codacy-coverage -r coverage.xml
