services:
  python_server:
    container_name: python_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    healthcheck:
      test: curl --fail http://localhost:8888/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    env_file:
      - .env
    environment:
      - ENVIRONMENT
      - HMAC_KEY
      - SAML_ENDPOINT_KEY
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
    restart: unless-stopped
    volumes:
      - ../databases:/usr/databases
      - ../media:/usr/media
      - ./config.toml:/usr/src/config.toml
    networks:
      - proxy

networks:
  proxy:
    external: true
