services:
  python_server:
    container_name: python_server

    # TODO (riley): remove network_mode once i figure out how to isolate ip ranges on the server
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    # scuffed way to keep the container running
    # TODO (riley): only have keyboard interaction when running in dev
    stdin_open: true
    tty: true
    volumes:
      - ../databases:/usr/databases
