services:
  python_server:
    container_name: python_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    # scuffed way to keep the container running
    # TODO (riley): only have keyboard interaction when running in dev
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ../databases:/usr/databases
    networks:
      - backend

networks:
  backend:
    name: backend
