
[server]
port = 8000
base_url = "http://localhost"
temporary_files = "./tmp"

[database]
databases = "./testing_databases"

[logging]
level = "INFO"
log_name = "aswwu"

[media]
media_path = "../media"

[development]
developer_id = 0

[mask]
current_year = 2324

[forms]
resumes = "../databases/resume"