ATTACH DATABASE '../databases/archives.db' AS ARCHIVE;

CREATE TABLE IF NOT EXISTS ARCHIVE.profiles1920 AS SELECT * FROM ARCHIVE.profiles1819 WHERE 0;

INSERT INTO ARCHIVE.profiles1920 SELECT * FROM main.profiles;