ATTACH DATABASE '../databases/archives.db' AS ARCHIVE;

CREATE TABLE IF NOT EXISTS ARCHIVE.profile1920 AS SELECT * FROM ARCHIVE.profile1819 WHERE 0;

INSERT INTO ARCHIVE.profile1920 SELECT * FROM main.profiles;