name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        bash scripts/pytest_setup.sh

    - name: Start Server in the background
      run: |
        bash scripts/run_pytests.sh

    - name: Prepare Artifact
      run: |
        mkdir ../backend-artifact
        mkdir ../backend-artifact/backend-payload
        cp scripts/remote_deploy.sh ../backend-artifact/
        cp scripts/server_deploy.sh ../backend-artifact/backend-payload
        cp ./ ../backend-artifact/backend-payload/python_server

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: server-log
        path: ../backend-artifact
