name: Python application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.3
      - name: Install dependencies
        run: |
          bash scripts/pytest_setup.sh
      - name: Run Tests
        run: |
          bash scripts/run_pytests.sh
