name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3
      - name: Install dependencies
        run: |
          bash scripts/setup_ci.sh
      - name: Run Tests
        run: |
          bash scripts/run_pytests.sh
